PROGRAM_NAME='DEFINITIONS_moduleCommands'

(***********************************************************)
(*               CONSTANT DEFINITIONS GO BELOW             *)
(***********************************************************)
DEFINE_CONSTANT

// non SNAPI channels
#IF_NOT_DEFINED WARMUP_FB
    WARMUP_FB				= 253
#END_IF

#IF_NOT_DEFINED COOLING_FB
    COOLING_FB				= 254
#END_IF

// module commands
#IF_NOT_DEFINED CMD_SET_PASSTHRU
    CHAR CMD_SET_PASSTHRU[]		= 'PASSTHRU-'
#END_IF 

#IF_NOT_DEFINED CMD_SET_PASSBACK
    CHAR CMD_SET_PASSBACK[]		= 'PASSBACK-'
#END_IF 

#IF_NOT_DEFINED CMD_SET_INPUT
    CHAR CMD_SET_INPUT[]		= 'INPUT-'
#END_IF

#IF_NOT_DEFINED CMD_SET_DIALID
    CHAR CMD_SET_DIALID[]		= 'DIALID-'
#END_IF

#IF_NOT_DEFINED CMD_SET_INPUTSELECT
    CHAR CMD_SET_INPUTSELECT[]		= 'INPUTSELECT-'
#END_IF

#IF_NOT_DEFINED CMD_SET_XCH
    CHAR CMD_SET_XCH[]			= 'XCH-'
#END_IF

#IF_NOT_DEFINED CMD_SET_HANGUPALL
    CHAR CMD_SET_HANGUPALL[]		= 'HANGUPALL'
#END_IF

#IF_NOT_DEFINED CMD_SET_DEBUG
    CHAR CMD_SET_ASPECT[]		= 'ASPECT-'
#END_IF

#IF_NOT_DEFINED CMD_SET_DEBUG
    CHAR CMD_SET_DEBUG[]		= 'DEBUG-'
#END_IF

#IF_NOT_DEFINED CMD_RESP_LAMPTIME
    CHAR CMD_RESP_LAMPTIME[]		= 'LAMPTIME-'
#END_IF

#IF_NOT_DEFINED CMD_SET_WARMUP_TIME
    CHAR CMD_SET_WARMUP_TIME[]		= 'WARMUP-'
#END_IF

#IF_NOT_DEFINED CMD_SET_COOLDOWN_TIME
    CHAR CMD_SET_COOLDOWN_TIME[]	= 'COOLDOWN-'
#END_IF

#IF_NOT_DEFINED CMD_SET_REINIT
    CHAR CMD_SET_REINIT[]		= 'REINIT'
#END_IF

#IF_NOT_DEFINED CMD_SET_INPUT_PROPERTY
    CHAR CMD_SET_INPUT_PROPERTY[]	= 'INPUTPROPERTY-'
#END_IF

#IF_NOT_DEFINED PARAM_INPUT_DIGITAL_1
    CHAR PARAM_INPUT_DIGITAL_1[]	= 'DIGITAL,1'
#END_IF

#IF_NOT_DEFINED PARAM_INPUT_HDMI_1
    CHAR PARAM_INPUT_HDMI_1[]		= 'HDMI,1'
#END_IF

#IF_NOT_DEFINED CMD_SET_PROPERTY
    CHAR CMD_SET_PROPERTY[]	 	= 'PROPERTY-'
#END_IF

#IF_NOT_DEFINED PARAM_IP_ADDRESS
    CHAR PARAM_IP_ADDRESS[]		= 'IP_Address,'
#END_IF

#IF_NOT_DEFINED PARAM_PORT
    CHAR PARAM_PORT[]			= 'Port,'
#END_IF

#IF_NOT_DEFINED PARAM_POLL_TIME
    CHAR PARAM_POLL_TIME[]		= 'Poll_Time,'
#END_IF

#IF_NOT_DEFINED PARAM_MAC_ADDRESS
    CHAR PARAM_MAC_ADDRESS[]		= 'MAC_Address,'
#END_IF

#IF_NOT_DEFINED PARAM_DEV_ID
    CHAR PARAM_DEV_ID[]			= 'Device_ID,'
#END_IF

#IF_NOT_DEFINED PARAM_PASSWORD
    CHAR PARAM_PASSWORD[]		= 'Password,'
#END_IF

#IF_NOT_DEFINED PARAM_INPUT_VIDEO
    CHAR PARAM_INPUT_VIDEO[]		= 'COMPOSITE,'
#END_IF

#IF_NOT_DEFINED PARAM_INPUT_SVIDEO
    CHAR PARAM_INPUT_SVIDEO[]		= 'SVIDEO,'
#END_IF

#IF_NOT_DEFINED PARAM_INPUT_COMP
    CHAR PARAM_INPUT_COMP[]		= 'COMPONENT,'
#END_IF

#IF_NOT_DEFINED PARAM_INPUT_VGA
    CHAR PARAM_INPUT_VGA[]		= 'VGA,'
#END_IF

#IF_NOT_DEFINED PARAM_INPUT_HDMI
    CHAR PARAM_INPUT_HDMI[]		= 'HDMI,'
#END_IF

#IF_NOT_DEFINED PARAM_INPUT_TV
    CHAR PARAM_INPUT_TV[]		= 'TV,'
#END_IF

// module responses / event listeners
#IF_NOT_DEFINED RESP_INPUT
    CHAR RESP_INPUT[]			= 'INPUT-'
#END_IF

#IF_NOT_DEFINED RESP_INPUTSELECT
    CHAR RESP_INPUTSELECT[]		= 'INPUTSELECT-'
#END_IF

#IF_NOT_DEFINED CMD_RESP_XCH
    CHAR CMD_RESP_XCH[]			= 'XCH-'
#END_IF

#IF_NOT_DEFINED RESP_STATUS_CONNECTED
    CHAR RESP_STATUS_CONNECTED[]	= 'DIALERSTATUS-CONNECTED'
#END_IF

#IF_NOT_DEFINED RESP_STATUS_IDLE
    CHAR RESP_STATUS_IDLE[]		= 'DIALERSTATUS-DISCONNECTED'
#END_IF